export const languageCodes: {
  [key: string]: {
    flag: string;
    language: string;
    translate: string;
    polly: string;
    polly_female_voice: string;
    polly_male_voice: string;
  };
} = {
  arab: {
    flag: "🇦🇪",
    language: "Arabic",
    translate: "ar",
    polly: "arab",
    polly_female_voice: "Zeina",
    polly_male_voice: "Zeina",
  },
  "cmn-CN": {
    flag: "🇨🇳",
    language: "Chinese, Mandarin",
    translate: "zh",
    polly: "cmn-CN",
    polly_female_voice: "Zhiyu",
    polly_male_voice: "Zhiyu",
  },
  "da-DK": {
    flag: "🇩🇰",
    language: "Danish",
    translate: "da",
    polly: "da-DK",
    polly_female_voice: "Naja",
    polly_male_voice: "Mads",
  },
  "nl-NL": {
    flag: "🇳🇱",
    language: "Dutch",
    translate: "nl",
    polly: "nl-NL",
    polly_female_voice: "Lotte",
    polly_male_voice: "Ruben",
  },
  "en-US": {
    flag: "🇺🇸",
    language: "English, US",
    translate: "en",
    polly: "en-US",
    polly_female_voice: "Joanna",
    polly_male_voice: "Matthew",
  },
  "fr-FR": {
    flag: "🇫🇷",
    language: "French",
    translate: "fr",
    polly: "fr-FR",
    polly_female_voice: "Celine",
    polly_male_voice: "Mathieu",
  },
  "hi-IN": {
    flag: "🇮🇳",
    language: "Hindi",
    translate: "hi",
    polly: "hi-IN",
    polly_female_voice: "Aditi",
    polly_male_voice: "Aditi",
  },
  "de-DE": {
    flag: "🇩🇪",
    language: "German",
    translate: "de",
    polly: "de-DE",
    polly_female_voice: "Marlene",
    polly_male_voice: "Hans",
  },
  "it-IT": {
    flag: "🇮🇹",
    language: "Italian",
    translate: "it",
    polly: "it-IT",
    polly_female_voice: "Carla",
    polly_male_voice: "Giorgio",
  },
  "ja-JP": {
    flag: "🇯🇵",
    language: "Japanese",
    translate: "ja",
    polly: "ja-JP",
    polly_female_voice: "Mizuki",
    polly_male_voice: "Takumi",
  },
  "ko-KR": {
    flag: "🇰🇷",
    language: "Korean",
    translate: "ko",
    polly: "ko-KR",
    polly_female_voice: "Seoyeon",
    polly_male_voice: "Seoyeon",
  },
  "nb-NO": {
    flag: "🇳🇴",
    language: "Norwegian",
    translate: "no",
    polly: "nb-NO",
    polly_female_voice: "Liv",
    polly_male_voice: "Liv",
  },
  "pl-PL": {
    flag: "🇵🇱",
    language: "Polish",
    translate: "pl",
    polly: "pl-PL",
    polly_female_voice: "Ewa",
    polly_male_voice: "Jan",
  },
  "pt-BR": {
    flag: "🇧🇷",
    language: "Portuguese, Brazilian",
    translate: "pt",
    polly: "pt-BR",
    polly_female_voice: "Camila",
    polly_male_voice: "Ricardo",
  },
  "pt-PT": {
    flag: "🇵🇹",
    language: "Portuguese, European",
    translate: "pt",
    polly: "pt-PT",
    polly_female_voice: "Ines",
    polly_male_voice: "Cristiano",
  },
  "ro-RO": {
    flag: "🇷🇴",
    language: "Romanian",
    translate: "ro",
    polly: "ro-RO",
    polly_female_voice: "Carmen",
    polly_male_voice: "Carmen",
  },
  "ru-RU": {
    flag: "🇷🇺",
    language: "Russian",
    translate: "ru",
    polly: "ru-RU",
    polly_female_voice: "Tatyana",
    polly_male_voice: "Maxim",
  },
  "es-ES": {
    flag: "🇪🇸",
    language: "Spanish, European",
    translate: "es",
    polly: "es-ES",
    polly_female_voice: "Conchita",
    polly_male_voice: "Enrique",
  },
  "es-MX": {
    flag: "🇲🇽",
    language: "Spanish, Mexican",
    translate: "es",
    polly: "es-MX",
    polly_female_voice: "Mia",
    polly_male_voice: "Mia",
  },
  "sv-SE": {
    flag: "🇸🇪",
    language: "Swedish",
    translate: "sv",
    polly: "sv-SE",
    polly_female_voice: "Astrid",
    polly_male_voice: "Astrid",
  },
  "tr-TR": {
    flag: "🇹🇷",
    language: "Turkish",
    translate: "tr",
    polly: "tr-TR",
    polly_female_voice: "Filiz",
    polly_male_voice: "Filiz",
  },
};
